### ISSUE TITLE
question on reshuffling training data

### ISSUE THREAD

**Issue by kevinkwl** [ymcui/Eval-on-NN-of-RC#2]
Hi, about the general tips for training, I know that reshuffling is a good way to go.
But for CBTest Data, I found out that the length of documents varies from ~200 to 800, isn't it more efficient to sort the training set by length and fetch minibatchs from the sorted set?

**Comment by ymcui** [comment]
Hi,
We did not try sorting the samples by the length order.
But generally speaking, it can effectively accelerate training speed.

Best,
Yiming
