### ISSUE TITLE
question on Gradient Clip setting

### ISSUE THREAD

**Issue by ZhuYunzong** [ymcui/Eval-on-NN-of-RC#3]
Thank u for sharing.
I have a simple question to ask. Setting the Gradient Clip in Keras means  "clipvalue = 5"　or  "clipnorm = 5" ?
Does "clipvalue"  work on every single value, and "clipnorm"  impose restrictions on the norm of matrix ?

**Comment by ymcui** [comment]
Hi,
`Gradient Clip` means to use `clipnorm`, not `clipvalue` in Keras optimizer.

Best,
Yiming

**Comment by ZhuYunzong** [comment]
Thank you. @ymcui
