### ISSUE TITLE
Embedding vector for replaced entities

### ISSUE THREAD

**Issue by sth4k** [ymcui/Eval-on-NN-of-RC#4]
Hi @ymcui , I am recently confused with a problem pertaining to the nature of the dataset. In the CNN/Daily Mail dataset, some NEs are replaced with @entity. My question is, of all the documents, is the same NE replaced by the same @entity? (e.g, CNN is always replaced by @entity1, in every document sample). If they are not the same, when we are using embedding vectors for @entity at the prediction stage, they are representing different words, would that cause problems?
I have this confusion because when i looked into the data, seems in different documents, they are replaced by different @entity . For example, @entity24:Shiite Muslims in one sample and @entity24:Domus Sanctae Marthae in another sample.

**Comment by ymcui** [comment]
Hi,
Q1: is the same NE replaced by the same @entity?
A1: No, the NE tokens are only valid **within** the document of sample. For e.g. `entity0` may refer to 'apple' in current sample, but `entity0` may be 'orange' in another sample.

Q2: ...they are representing different words, would that cause problems?
A2: The entity tokens are only representing a specific NE within the document, it does not represent any real NE. In this situation, the embeddings of `@entityX` are only used as discriminating different NEs in the document. You can just treat it as normal words.

Yiming
